### ISSUE TITLE
Bullet damage does not work after the November 16 update

### ISSUE THREAD

**Issue by OO0000O** [Mikusch/fortress-royale#46]
After the November 16 update, bullets no longer deal damage to opponents.

Only projectile types like Syringe Guns and Wrap Assassins do damage.

**Comment by FortyTwoFortyTwo** [comment]
I've tested with Scattergun and Pistol in both windows and linux server, works fine for me, make sure your plugin and gamedata is up to date. Are you using windows or linux, or were there any errors or crash log you could post?

**Comment by OO0000O** [comment]
All plugins and game data files are up to date, but still bullet damage doesn't work.  

But it seems that the dhook plugin is not turned on properly.

I'm getting this error in the plugin.

> [SM] Unable to load plugin "dhooks-test.smx": Error detected in plugin startup (see error logs)

**Comment by FortyTwoFortyTwo** [comment]
`dhooks-test.smx` is just an example plugin for dhooks, shouldn't be related to this. Check in errors log from `addons/sourcemod/logs` to find any errors related to royale plugin, or one of the extension and plugin using this (dhooks ext, tf_econ_data plugin and tf2attributes plugin)

**Comment by OO0000O** [comment]
I checked again, and bullet damage didn't work in Battle Royale if the server has the Slender Fortress 2 plugin.

There was no problem in the past, but it seems that a problem occurred while Slender Fortress 2 was updated.

**Comment by FortyTwoFortyTwo** [comment]
It should in theory work fine if both Fortress Royale and Slender Fortress 2 are not enabled at the same time, but both plugins are huge and are in bound for bugs. It would be better to not have both plugins loaded at the same time instead of letting enabled convar do the job.

I still can't say much on why your side broke without knowing more specific on why so with logs

**Comment by FortyTwoFortyTwo** [comment]
Okay, turns out I actually have similar issue to what you have, but only have this issue in a different server I tested it. It's something to do with SDKHook's handling with `ShouldCollide` hook, i'm not too sure exactly whats going on, but [switching to dhooks fixes it for me](https://github.com/Mikusch/fortress-royale/commit/10f0c6ab83baab938e4798ce57f691856000c486).
Try out this fix, and make no other plugin uses SDKHook's `ShouldCollide`
